### ISSUE TITLE
Does it support Landscape mode ?

### ISSUE THREAD

**Issue by comeonyoh** [navermaps/maps.ios#2]
I `m testing your map service...

and I found it does not support landscape mode,  right?

I have not found any mentions about it

let me know please

thanks~

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <[navermap-ios-api] Does it support Landscape mode ? (#2)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-12-24 10:00 ~ 2015-12-31 23:59 GMT +09:00]<br>리프레쉬 휴가입니다. <br>Pinpoint는 Pinpoint DL로 문의주시기 바랍니다. 
--------------------------------------------
