### ISSUE TITLE
(IOS/Obj-C)NaverCafeSDK/NMapViewerSDK framework 을 추가시 duplicate symbol 오류

### ISSUE THREAD

**Issue by jyj1127j** [navermaps/maps.ios#5]
여기에 관련 문의를 하는 것이 맞는지 모르겠지만...
문의처를 몰라 문의 드려봅니다.

Object-c 환경의 NaverCafeSDK를 사용 하는 프로젝트에
NMapViewerSDK를 추가하여 빌드하면 아래와 같이 duplicate symbol 오류가 발생합니다.

이런 경우 어떻게 처리해야 할지 몰라 문의 드립니다. 

duplicate symbol OBJCCLASS_$_NBase64 in:
FNMapViewerSDK.framework/NMapViewerSDK(NBase64.o)
NaverCafeSDK.framework/NaverCafeSDK(NBase64.o)
duplicate symbol OBJCMETACLASS_$_NBase64 in:
NMapViewerSDK.framework/NMapViewerSDK(NBase64.o)
NaverCafeSDK.framework/NaverCafeSDK(NBase64.o)
duplicate symbol OBJCCLASS_$_NHMacUtil in: 
NMapViewerSDK.framework/NMapViewerSDK(NHMacUtil.o)
NaverCafeSDK.framework/NaverCafeSDK(NHMacUtil.o)
duplicate symbol OBJCMETACLASS_$_NHMacUtil in:
NMapViewerSDK.framework/NMapViewerSDK(NHMacUtil.o)
NaverCafeSDK.framework/NaverCafeSDK(NHMacUtil.o)
duplicate symbol OBJCCLASS_$_NMacCommonManager in:
NMapViewerSDK.framework/NMapViewerSDK(NMacCommonManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NMacCommonManager.o)
duplicate symbol OBJCMETACLASS_$_NMacCommonManager in:
NMapViewerSDK.framework/NMapViewerSDK(NMacCommonManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NMacCommonManager.o)
duplicate symbol OBJCCLASS_$_NMacManager in:
NMapViewerSDK.framework/NMapViewerSDK(NMacManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NMacManager.o)
duplicate symbol OBJCMETACLASS_$_NMacManager in:
NMapViewerSDK.framework/NMapViewerSDK(NMacManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NMacManager.o)
duplicate symbol OBJCCLASS_$_NServiceMacManager in:
NMapViewerSDK.framework/NMapViewerSDK(NServiceMacManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NServiceMacManager.o)
duplicate symbol OBJCMETACLASS_$_NServiceMacManager in:
NMapViewerSDK.framework/NMapViewerSDK(NServiceMacManager.o)
NaverCafeSDK.framework/NaverCafeSDK(NServiceMacManager.o)
duplicate symbol OBJCCLASS_$_NURLEncoder in:
NMapViewerSDK.framework/NMapViewerSDK(NURLEncoder.o)
NaverCafeSDK.framework/NaverCafeSDK(NURLEncoder.o)
duplicate symbol OBJCMETACLASS_$_NURLEncoder in:
NMapViewerSDK.framework/NMapViewerSDK(NURLEncoder.o)
NaverCafeSDK.framework/NaverCafeSDK(NURLEncoder.o)
ld: 12 duplicate symbols for architecture x86_64

**Comment by mrtajo** [comment]
안녕하세요. 
불편을 끼쳐드려 죄송합니다. 카페와 지도에서 각각 사용한 모듈끼리의 충돌인데요.
https://github.com/navermaps/maps.ios/releases 에서 v2.0.19 버전을 받으셔서, ApiGateway 는 빼고 NMapViewer staticLibrary 로 지도를 사용하시면 일단 회피하실 수 있습니다.
모듈 충돌 이슈는 빠른 시일 내에 해결 하겠습니다.
네이버 지도 SDK 를 사용해주셔서 감사합니다.

ps) http://forum.developers.naver.com/ 로 질문 주시면 보다 빠르게 답변 드릴 수 있습니다.

**Comment by mrtajo** [comment]
안녕하세요.
v2.1.2 릴리즈 완료하였습니다.
카페 쪽과 충돌이 발생한 라이브러리를 별도의 framework (ApiGatewayMac) 로 제공하도록 변경하였습니다.
이 라이브러리의 경우 시뮬레이터에서 개발/테스트 하기 위해 Universal dynamic framework 로 구현되었는데요.
문제는 앱을 App store 에 제출할 때, i386 코드로 인해 제출이 거부되는 fat binary 이슈가 공존하는 점입니다.
이를 해결하기 위해 strip framework script 까지 제공하오니, 참고하셔서 앱 개발에 사용해 주셔요.
자세한 설명은 https://developers.naver.com/docs/map/ios/ 에서 확인 부탁 드립니다.
네이버 지도 SDK 를 사용해주셔서 감사합니다.
