### ISSUE TITLE
Bitcode지원

### ISSUE THREAD

**Issue by garyoo** [navermaps/maps.ios#6]
지원 되나요?

**Comment by mrtajo** [comment]
안녕하세요.
https://github.com/navermaps/maps.ios/releases 에서 v2.0.19 부터 bitcode 를 지원합니다.

네이버 지도 SDK 를 사용해주셔서 감사합니다.

**Comment by garyoo** [comment]
build는 성공하는데 archive만 하면 아래와 같은 오류가 뜨네요.
혹시 어떤 문제인지 알 수 있을까요?

ld: bitcode bundle could not be generated because '/.../NMapViewerSDK.framework/NMapViewerSDK(NMapVersionData.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by humdrum** [comment]
v2.1.1 에서 수정 되었습니다. 

네이버 지도 SDK 를 사용해주셔서 감사합니다.

**Comment by garyoo** [comment]
확인되었습니다. 감사합니다.
