### ISSUE TITLE
Archive 관련 문의

### ISSUE THREAD

**Issue by garyoo** [navermaps/maps.ios#7]
build는 성공하는데 archive만 하면 아래와 같은 오류가 뜨네요.
혹시 어떤 문제인지 알 수 있을까요?

ld: bitcode bundle could not be generated because '/.../NMapViewerSDK.framework/NMapViewerSDK(NMapVersionData.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mrtajo** [comment]
안녕하세요. 
문의주신 bitcode 관련 오류를 확인하였습니다.
관련해서 v2.1.1 버전을 이번 주 내에 배포할 예정이오니 조금만 기다려주세요.
네이버지도 SDK 를 사용해주셔서 감사합니다.
